version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.11

executors:
  default:
    docker:
      - image: circleci/node:10

commands:
  ls:
    steps:
      - run:
          name: show dirctories
          command: |
            ls -R | grep ":" | sed -e 's/://' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'
  npm_install:
    steps:
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          working_directory: client
          name: install npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - client/node_modules

jobs:
  build:
    executor: default
    working_directory: ~/repo
    steps:
      - checkout
      - ls
      - npm_install

  deploy:
    executor: default
    working_directory: ~/repo
    steps:
      - checkout
      - npm_install
      - ls
      - run:
          working_directory: client
          name: build
          command: |
            npx tsc
            npx webpack
      - aws-s3/sync:
          from: dist
          to: s3://takasho-web-estimate-frontend-dev2
          overwrite: true

workflows:
  version: 2
  continuous-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: develop